; This file was auto-generated by drush apigee-release
core = 7.x

api = 2
projects[drupal][version] = "7.21"

; Modules
projects[accordion_menu][subdir] = "contrib"
projects[accordion_menu][version] = "1.2"

projects[acl][subdir] = "contrib"
projects[acl][version] = "1.0"

projects[views_bulk_operations][subdir] = "contrib"
projects[views_bulk_operations][version] = "3.1"

projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.0-beta4"

projects[admin][subdir] = "contrib"
projects[admin][version] = "2.0-beta3"

projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[util][subdir] = "contrib"
projects[util][version] = "1.0-rc1"

projects[admin_views][subdir] = "contrib"
projects[admin_views][version] = "1.2"

projects[advanced_forum][subdir] = "contrib"
projects[advanced_forum][version] = "2.3"

projects[amazons3][subdir] = "contrib"
projects[amazons3][version] = "1.0-beta7"

projects[apachesolr][subdir] = "contrib"
projects[apachesolr][version] = "1.3"

projects[apachesolr_autocomplete][subdir] = "contrib"
projects[apachesolr_autocomplete][version] = "1.3"

projects[apachesolr_stats][subdir] = "contrib"
projects[apachesolr_stats][version] = "1.0-alpha1"

projects[appbar][subdir] = "contrib"
projects[appbar][version] = "2.0"

projects[author_pane][subdir] = "contrib"
projects[author_pane][version] = "2.0-beta1"

projects[autologout][subdir] = "contrib"
projects[autologout][version] = "2.0-beta1"

projects[awssdk][subdir] = "contrib"
projects[awssdk][version] = "5.4"

projects[back_to_top][subdir] = "contrib"
projects[back_to_top][version] = "1.3"

projects[backbone][subdir] = "contrib"
projects[backbone][version] = "1.x-dev"

projects[backup_migrate][subdir] = "contrib"
projects[backup_migrate][version] = "2.5"

projects[service_links][subdir] = "contrib"
projects[service_links][version] = "2.2"

projects[block_class][subdir] = "contrib"
projects[block_class][version] = "1.2"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.3"

projects[captcha][subdir] = "contrib"
projects[captcha][version] = "1.0"

projects[cck_phone][subdir] = "contrib"
projects[cck_phone][version] = "1.x-dev"

projects[cdn][subdir] = "contrib"
projects[cdn][version] = "2.6"

projects[chart][subdir] = "contrib"
projects[chart][version] = "1.1"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.13"

projects[ckeditor_link][subdir] = "contrib"
projects[ckeditor_link][version] = "2.3"

projects[commerce][subdir] = "contrib"
projects[commerce][version] = "1.8"

projects[commerce_custom_line_items][subdir] = "contrib"
projects[commerce_custom_line_items][version] = "1.x-dev"

projects[connector][subdir] = "contrib"
projects[connector][version] = "1.0-beta2"

projects[content_access][subdir] = "contrib"
projects[content_access][version] = "1.2-beta2"

projects[contentapi][subdir] = "contrib"
projects[contentapi][version] = "1.0-alpha3"

projects[context][subdir] = "contrib"
projects[context][version] = "3.0-beta6"

projects[cnr][subdir] = "contrib"
projects[cnr][version] = "4.22"

projects[cpn][subdir] = "contrib"
projects[cpn][version] = "1.4"

projects[facetapi][subdir] = "contrib"
projects[facetapi][version] = "1.3"

projects[custom_breadcrumbs][subdir] = "contrib"
projects[custom_breadcrumbs][version] = "1.0-alpha1"

projects[date][subdir] = "contrib"
projects[date][version] = "2.6"

projects[deploy][subdir] = "contrib"
projects[deploy][version] = "2.0-alpha2"

projects[devconnect][type] = "module"
projects[devconnect][download][type] = "git"
projects[devconnect][download][url] = "git@github.com:apigee/devconnect.git"
projects[devconnect][download][branch] = "7.x-4.22"
projects[devconnect][download][revision] = "e3956ab58a0b7d8f34a00174323f27e8d4b81608"
projects[devconnect][subdir] = "custom"

projects[devconnect_content_admin][type] = "module"
projects[devconnect_content_admin][subdir] = "custom/devconnect"
projects[devconnect_content_admin][version] = "1.0"

projects[devconnect_content_authoring][type] = "module"
projects[devconnect_content_authoring][subdir] = "custom/devconnect"
projects[devconnect_content_authoring][version] = "1.0"

projects[devconnect_download][type] = "module"
projects[devconnect_download][subdir] = "custom/devconnect"
projects[devconnect_download][version] = "1.0"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.3"

projects[diff][subdir] = "contrib"
projects[diff][version] = "2.0"

projects[domain][subdir] = "contrib"
projects[domain][version] = "3.10"

projects[domain_ctools][subdir] = "contrib"
projects[domain_ctools][version] = "1.3"

projects[domain_views][subdir] = "contrib"
projects[domain_views][version] = "1.5"

projects[download_file][subdir] = "contrib"
projects[download_file][version] = "1.1"

projects[ds][subdir] = "contrib"
projects[ds][version] = "1.8"

projects[eck][subdir] = "contrib"
projects[eck][version] = "2.0-rc2"

projects[fontyourface][subdir] = "contrib"
projects[fontyourface][version] = "2.8"

projects[encset][subdir] = "contrib"
projects[encset][version] = "1.3"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.1"

projects[entity_dependency][subdir] = "contrib"
projects[entity_dependency][version] = "1.0-alpha1"

projects[entityreference][subdir] = "contrib"
projects[entityreference][version] = "1.0"

projects[fape][subdir] = "contrib"
projects[fape][version] = "1.1"

projects[faq][subdir] = "contrib"
projects[faq][version] = "1.0-rc2"

projects[features][subdir] = "contrib"
projects[features][version] = "1.0"

projects[feeds_tamper][subdir] = "contrib"
projects[feeds_tamper][version] = "1.0-beta4"

projects[feeds_xpathparser][subdir] = "contrib"
projects[feeds_xpathparser][version] = "1.0-beta4"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.1"

projects[field_permissions][subdir] = "contrib"
projects[field_permissions][version] = "1.0-beta2"

projects[media][subdir] = "contrib"
projects[media][version] = "1.3"

projects[styles][subdir] = "contrib"
projects[styles][version] = "2.0-alpha8"

projects[fivestar][subdir] = "contrib"
projects[fivestar][version] = "2.0-alpha2"

projects[flood_control][subdir] = "contrib"
projects[flood_control][version] = "1.0"

projects[footermap][subdir] = "contrib"
projects[footermap][version] = "1.1"

projects[genpass][subdir] = "contrib"
projects[genpass][version] = "1.0"

projects[gist_filter][subdir] = "contrib"
projects[gist_filter][version] = "1.2"

projects[git_deploy][subdir] = "contrib"
projects[git_deploy][version] = "2.2"

projects[github_connect][subdir] = "contrib"
projects[github_connect][version] = "1.1"

projects[gmap][subdir] = "contrib"
projects[gmap][version] = "1.1-beta2"

projects[google_analytics_reports][subdir] = "contrib"
projects[google_analytics_reports][version] = "1.3"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.3"

projects[gravatar][subdir] = "contrib"
projects[gravatar][version] = "1.1"

projects[hansel][subdir] = "contrib"
projects[hansel][version] = "1.3"

projects[http_client][subdir] = "contrib"
projects[http_client][version] = "2.4"

projects[imagemagick][subdir] = "contrib"
projects[imagemagick][version] = "1.0"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.7"

projects[imce_tools][version] = "1.1"
projects[imce_tools][subdir] = "contrib"

projects[imce_mkdir][subdir] = "contrib"
projects[imce_mkdir][version] = "1.0"

projects[imce_wysiwyg][subdir] = "contrib"
projects[imce_wysiwyg][version] = "1.0"

projects[import_html][subdir] = "contrib"
projects[import_html][version] = "1.x-dev"

projects[itoggle][subdir] = "contrib"
projects[itoggle][version] = "2.3"

projects[jcarousel][subdir] = "contrib"
projects[jcarousel][version] = "2.6"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[journal][subdir] = "contrib"
projects[journal][version] = "1.0"

projects[jquery_colorpicker][subdir] = "contrib"
projects[jquery_colorpicker][version] = "1.0-rc2"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.3"

projects[jquerymobile][subdir] = "contrib"
projects[jquerymobile][version] = "2.0-beta1"

projects[ldap][subdir] = "contrib"
projects[ldap][version] = "1.0-beta12"

projects[legal][subdir] = "contrib"
projects[legal][version] = "1.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[link][subdir] = "contrib"
projects[link][version] = "1.1"

projects[link_node][subdir] = "contrib"
projects[link_node][version] = "1.0"

projects[linkchecker][subdir] = "contrib"
projects[linkchecker][version] = "1.1"

projects[location][subdir] = "contrib"
projects[location][version] = "3.0-rc2"

projects[login_destination][subdir] = "contrib"
projects[login_destination][version] = "1.1"

projects[logintoboggan][subdir] = "contrib"
projects[logintoboggan][version] = "1.3"

projects[markdown][subdir] = "contrib"
projects[markdown][version] = "1.1"

projects[mass_contact][subdir] = "contrib"
projects[mass_contact][version] = "1.0-beta2"

projects[me][subdir] = "contrib"
projects[me][version] = "1.1"

projects[media_youtube][subdir] = "contrib"
projects[media_youtube][version] = "1.0-beta3"

projects[mediaelement][subdir] = "contrib"
projects[mediaelement][version] = "1.2"

projects[memcache][subdir] = "contrib"
projects[memcache][version] = "1.0"

projects[menu_item_visibility][subdir] = "contrib"
projects[menu_item_visibility][version] = "1.0-beta1"

projects[menu_trail_by_path][subdir] = "contrib"
projects[menu_trail_by_path][version] = "2.0"

projects[message][subdir] = "contrib"
projects[message][version] = "1.9"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-beta7"

projects[metatags_quick][subdir] = "contrib"
projects[metatags_quick][version] = "2.7"

projects[migrate][subdir] = "contrib"
projects[migrate][version] = "2.5"

projects[module_filter][subdir] = "contrib"
projects[module_filter][version] = "1.7"

projects[multiblock][subdir] = "contrib"
projects[multiblock][version] = "1.1"

projects[nagios][subdir] = "contrib"
projects[nagios][version] = "1.2"

projects[node_embed][subdir] = "contrib"
projects[node_embed][version] = "1.1"

projects[node_export][subdir] = "contrib"
projects[node_export][version] = "3.0"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[oauthconnector][subdir] = "contrib"
projects[oauthconnector][version] = "1.0-beta2"

projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.1"

projects[og][subdir] = "contrib"
projects[og][version] = "1.5"

projects[omega_tools][subdir] = "contrib"
projects[omega_tools][version] = "3.0-rc4"

projects[page_title][subdir] = "contrib"
projects[page_title][version] = "2.7"

projects[panelizer][subdir] = "contrib"
projects[panelizer][version] = "2.0"

projects[panels][subdir] = "contrib"
projects[panels][version] = "3.3"

projects[panels_everywhere][subdir] = "contrib"
projects[panels_everywhere][version] = "1.0-rc1"

projects[password_policy][subdir] = "contrib"
projects[password_policy][version] = "1.3"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[permission_grid][subdir] = "contrib"
projects[permission_grid][version] = "1.2"

projects[persistent_login][subdir] = "contrib"
projects[persistent_login][version] = "1.0-beta1"

projects[prettify][subdir] = "contrib"
projects[prettify][version] = "1.0-beta1"

projects[querypath][subdir] = "contrib"
projects[querypath][version] = "2.1"

projects[rate][subdir] = "contrib"
projects[rate][version] = "1.6"
projects[rate][patches][] = "http://drupal.org/files/rate-change_1903262_1.patch"

projects[readonlymode][subdir] = "contrib"
projects[readonlymode][version] = "1.1"

projects[recaptcha][subdir] = "contrib"
projects[recaptcha][version] = "1.9"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[register_preapproved][subdir] = "contrib"
projects[register_preapproved][version] = "1.0-beta2"

projects[services][subdir] = "contrib"
projects[services][version] = "3.4"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.3"

projects[sass][subdir] = "contrib"
projects[sass][version] = "2.0"

projects[scanner][subdir] = "contrib"
projects[scanner][version] = "1.x-dev"

projects[search_api][subdir] = "contrib"
projects[search_api][version] = "1.7"

projects[search_api_ajax][subdir] = "contrib"
projects[search_api_ajax][version] = "1.1"

projects[search_api_attachments][subdir] = "contrib"
projects[search_api_attachments][version] = "1.2"

projects[search_api_autocomplete][subdir] = "contrib"
projects[search_api_autocomplete][version] = "1.0"

projects[search_api_facets_paths][subdir] = "contrib"
projects[search_api_facets_paths][version] = "1.9"

projects[search_api_live_results][subdir] = "contrib"
projects[search_api_live_results][version] = "1.x-dev"

projects[search_api_location][subdir] = "contrib"
projects[search_api_location][version] = "2.x-dev"

projects[search_api_multi][subdir] = "contrib"
projects[search_api_multi][version] = "1.0"

projects[search_api_page][subdir] = "contrib"
projects[search_api_page][version] = "1.0-rc1"

projects[search_api_ranges][subdir] = "contrib"
projects[search_api_ranges][version] = "1.4"

projects[search_api_solr][subdir] = "contrib"
projects[search_api_solr][version] = "1.1"

projects[search_api_sorts][subdir] = "contrib"
projects[search_api_sorts][version] = "1.4"

projects[securelogin][subdir] = "contrib"
projects[securelogin][version] = "1.4"

projects[selenium][subdir] = "contrib"
projects[selenium][version] = "2.0-beta2"

projects[services_views][subdir] = "contrib"
projects[services_views][version] = "1.0-beta2"

projects[smtp][subdir] = "contrib"
projects[smtp][version] = "1.0"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][version] = "2.0"

projects[statsd][subdir] = "contrib"
projects[statsd][version] = "1.0"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

projects[taxonomy_access][subdir] = "contrib"
projects[taxonomy_access][version] = "1.0-rc1"

projects[textformatter][subdir] = "contrib"
projects[textformatter][version] = "1.3"

projects[toc_filter][subdir] = "contrib"
projects[toc_filter][version] = "1.2"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[twitter][subdir] = "contrib"
projects[twitter][version] = "3.3"

projects[uuid][subdir] = "contrib"
projects[uuid][version] = "1.0-alpha4+2-dev"

projects[variable][subdir] = "contrib"
projects[variable][version] = "2.2"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[views_accordion][subdir] = "contrib"
projects[views_accordion][version] = "1.0-rc2"

projects[highcharts][subdir] = "contrib"
projects[highcharts][version] = "1.0-alpha6"

projects[views_slideshow][subdir] = "contrib"
projects[views_slideshow][version] = "3.0"

projects[votingapi][subdir] = "contrib"
projects[votingapi][version] = "2.11"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.19"

projects[weight][subdir] = "contrib"
projects[weight][version] = "2.3"

projects[workbench][subdir] = "contrib"
projects[workbench][version] = "1.2"

projects[workflow][subdir] = "contrib"
projects[workflow][version] = "1.2"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[xautoload][subdir] = "contrib"
projects[xautoload][version] = "2.7"

projects[XHProf][subdir] = "contrib"
projects[XHProf][version] = "1.0-beta2"

; Themes
projects[rubik][version] = "4.0-beta8"

projects[tao][version] = "3.0-beta4"

; Modules
projects[apigee_sso][type] = "module"
projects[apigee_sso][download][type] = "git"
projects[apigee_sso][download][url] = "git@github.com:apigee/apigee_drupal_sso.git"
projects[apigee_sso][download][revision] = "8e920e13c24ea2e822a6ba01bbba8cf6de7e6c45"
projects[apigee_sso][subdir] = "custom"

projects[commerce_worldpay_business_gateway][type] = "module"
projects[commerce_worldpay_business_gateway][download][type] = "git"
projects[commerce_worldpay_business_gateway][download][url] = "http://git.drupal.org/sandbox/magicmyth/1433370.git"
projects[commerce_worldpay_business_gateway][download][branch] = "7.x-1.x"
projects[commerce_worldpay_business_gateway][download][revision] = "4692f267a99d2af628eb569d12fba861d1aedd03"

projects[feeds][type] = "module"
projects[feeds][download][type] = "git"
projects[feeds][download][url] = "http://git.drupal.org/project/feeds.git"
projects[feeds][download][branch] = "(no branch)"
projects[feeds][download][revision] = "3eb5a48643e1ae848ac03fbfc060492c507a9a42"

; Themes
projects[apigee_base][type] = "theme"
projects[apigee_base][download][type] = "git"
projects[apigee_base][download][url] = "git@github.com:apigee/apigee_drupal_base_theme.git"
projects[apigee_base][download][branch] = "devconnect"
projects[apigee_base][download][revision] = "f25b8c9497328ea82c89d18dfbb29fad0a2a745b"

projects[apigee_devconnect][type] = "theme"
projects[apigee_devconnect][download][type] = "git"
projects[apigee_devconnect][download][url] = "git@github.com:apigee/apigee_drupal_devconnect_theme.git"
projects[apigee_devconnect][download][branch] = "7.x-4.22"
projects[apigee_devconnect][download][revision] = "af4baaebb19e104f39866208f6fc4428ed508e62"

; Libraries
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"
libraries[backbone][download][url] = "git://github.com/documentcloud/backbone.git"
libraries[backbone][download][tag] = "0.9.2"
libraries[backbone][download][type] = "git"
libraries[backbone][destination] = "libraries"

libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"
libraries[json2][download][url] = "git://github.com/douglascrockford/JSON-js.git"
libraries[json2][download][type] = "git"
libraries[json2][destination] = "libraries"

libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
libraries[SolrPhpClient][type] = "library"
libraries[SolrPhpClient][download][url] = "http://solr-php-client.googlecode.com/files/SolrPhpClient.r60.2011-05-04.zip"
libraries[SolrPhpClient][download][type] = "get"
libraries[SolrPhpClient][destination] = "libraries"

libraries[glip][directory_name] = "glip"
libraries[glip][type] = "library"
libraries[glip][download][url] = "git://github.com/halstead/glip.git"
libraries[glip][download][type] = "git"
libraries[glip][destination] = "libraries"

libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"
libraries[jquery.cycle][download][url] = "http://www.malsup.com/jquery/cycle/release/jquery.cycle.zip?v2.86"
libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][destination] = "libraries"

libraries[jquery.selectlist][directory_name] = "jquery.selectlist"
libraries[jquery.selectlist][type] = "library"
libraries[jquery.selectlist][download][url] = "http://odyniec.net/projects/selectlist/jquery.selectlist-0.6.1.zip"
libraries[jquery.selectlist][download][type] = "get"
libraries[jquery.selectlist][destination] = "libraries"

libraries[colorpicker][directory_name] = "colorpicker"
libraries[colorpicker][type] = "library"
libraries[colorpicker][download][url] = "http://www.eyecon.ro/colorpicker/colorpicker.zip"
libraries[colorpicker][download][type] = "get"
libraries[colorpicker][destination] = "libraries"

libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"
libraries[tinymce][download][url] = "http://cloud.github.com/downloads/tinymce/tinymce/tinymce_3.4.7.zip"
libraries[tinymce][download][type] = "get"
libraries[tinymce][destination] = "libraries"

libraries[mediaelement][directory_name] = "mediaelement"
libraries[mediaelement][type] = "library"
libraries[mediaelement][download][url] = "https://nodeload.github.com/johndyer/mediaelement/zipball/master"
libraries[mediaelement][download][type] = "get"
libraries[mediaelement][destination] = "libraries"

libraries[s3-php5-curl][directory_name] = "s3-php5-curl"
libraries[s3-php5-curl][type] = "library"
libraries[s3-php5-curl][download][url] = "http://amazon-s3-php-class.googlecode.com/files/s3-php5-curl_0.4.0.tar.gz"
libraries[s3-php5-curl][download][type] = "get"
libraries[s3-php5-curl][destination] = "libraries"

libraries[codemirror][directory_name] = "codemirror"
libraries[codemirror][type] = "library"
libraries[codemirror][download][url] = "http://codemirror.net/codemirror.zip"
libraries[codemirror][download][type] = "get"
libraries[codemirror][destination] = "libraries"

libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.4/ckeditor_3.6.4.zip"
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][destination] = "libraries"

libraries[highcharts][directory_name] = "highcharts"
libraries[highcharts][type] = "library"
libraries[highcharts][download][url] = "http://www.highcharts.com/downloads/zips/Highcharts-2.2.5.zip"
libraries[highcharts][download][type] = "get"
libraries[highcharts][destination] = "libraries"

libraries[prettify][directory_name] = "prettify"
libraries[prettify][type] = "library"
libraries[prettify][download][url] = "http://google-code-prettify.googlecode.com/files/prettify-small-4-Mar-2013.tar.bz2"
libraries[prettify][download][type] = "get"
libraries[prettify][destination] = "libraries"

libraries[spyc][directory_name] = "spyc"
libraries[spyc][type] = "library"
libraries[spyc][download][url] = "http://spyc.googlecode.com/files/spyc-0.5.zip"
libraries[spyc][download][type] = "get"
libraries[spyc][destination] = "libraries"

libraries[awssdk][directory_name] = "awssdk"
libraries[awssdk][type] = "library"
libraries[awssdk][download][url] = "http://pear.amazonwebservices.com/get/sdk-latest.zip"
libraries[awssdk][download][type] = "get"
libraries[awssdk][destination] = "libraries"

